name: Main pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache pnpm dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install pnpm
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pnpm test

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: pnpm lint
